apiVersion: v1
items:
- apiVersion: nvidia.com/v1alpha1
  kind: DynamoWorkerMetadata
  metadata:
    creationTimestamp: "2026-05-06T05:12:07Z"
    generation: 5
    name: dynamo-combined-vllm-decodeworker-ae74a2d2-555fdcddb8-hxn6w
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: false
      controller: true
      kind: Pod
      name: dynamo-combined-vllm-decodeworker-ae74a2d2-555fdcddb8-hxn6w
      uid: a419940a-381e-4f1e-a60e-8d71ff630a7f
    resourceVersion: "249527716"
    uid: 0e451fc9-157f-43de-8c7a-a8bb0bedb957
  spec:
    data:
      endpoints:
        default-dynamo-combined-vllm-ae74a2d2/backend/clear_kv_blocks/1fa7eb180bea93:
          component: backend
          device_type: cpu
          endpoint: clear_kv_blocks
          instance_id: 8910352440617619
          namespace: default-dynamo-combined-vllm-ae74a2d2
          transport:
            tcp: 10.1.3.30:41827/1fa7eb180bea93/clear_kv_blocks
          type: Endpoint
        default-dynamo-combined-vllm-ae74a2d2/backend/generate/1fa7eb180bea93:
          component: backend
          device_type: cpu
          endpoint: generate
          instance_id: 8910352440617619
          namespace: default-dynamo-combined-vllm-ae74a2d2
          transport:
            tcp: 10.1.3.30:41827/1fa7eb180bea93/generate
          type: Endpoint
        default-dynamo-combined-vllm-ae74a2d2/backend/get_perf_metrics/1fa7eb180bea93:
          component: backend
          device_type: cpu
          endpoint: get_perf_metrics
          instance_id: 8910352440617619
          namespace: default-dynamo-combined-vllm-ae74a2d2
          transport:
            tcp: 10.1.3.30:41827/1fa7eb180bea93/get_perf_metrics
          type: Endpoint
      event_channels:
        default-dynamo-combined-vllm-ae74a2d2//kv_metrics/1fa7eb180bea93:
          component: ""
          instance_id: 8910352440617619
          namespace: default-dynamo-combined-vllm-ae74a2d2
          topic: kv_metrics
          transport:
            config:
              subject_prefix: namespace.default-dynamo-combined-vllm-ae74a2d2
            kind: Nats
          type: EventChannel
      model_cards:
        default-dynamo-combined-vllm-ae74a2d2/backend/generate/1fa7eb180bea93:
          card_json:
            context_length: 4096
            display_name: meta-llama/Llama-3.1-8B-Instruct
            gen_config:
              hf_generation_config_json:
                checksum: blake3:0523e4e0a4dd34381ea42fcf70a9e5130722c59b6c8425d5efdecac386c2790d
                path: hf://meta-llama/Llama-3.1-8B-Instruct/generation_config.json
            kv_cache_block_size: 16
            media_decoder: null
            media_fetcher: null
            migration_limit: 0
            model_info:
              hf_config_json:
                checksum: blake3:35526c33568b4823f63765ea29c1b2780659caddec1724adb057cc2495205f51
                path: hf://meta-llama/Llama-3.1-8B-Instruct/config.json
            model_input: Tokens
            model_type: Chat | Completions
            prompt_formatter:
              hf_tokenizer_config_json:
                checksum: blake3:ea3865c7f6f322eeab4d3a61ea83102e19bcfefb5b9022acf16b8ffeaabf21c9
                path: hf://meta-llama/Llama-3.1-8B-Instruct/tokenizer_config.json
            runtime_config:
              data_parallel_size: 1
              data_parallel_start_rank: 0
              enable_eagle: false
              enable_local_indexer: false
              exclude_tools_when_tool_choice_none: true
              max_num_batched_tokens: 8192
              max_num_seqs: 1024
              reasoning_parser: null
              tool_call_parser: null
              total_kv_blocks: 25731
            slug: meta-llama_llama-3_1-8b-instruct
            source_path: meta-llama/Llama-3.1-8B-Instruct
            tokenizer:
              hf_tokenizer_json:
                checksum: blake3:6c628c92d1623f93fe811c3974c81fbc415d776f33cc440d44ee6c7d9ed9e066
                path: hf://meta-llama/Llama-3.1-8B-Instruct/tokenizer.json
          component: backend
          endpoint: generate
          instance_id: 8910352440617619
          namespace: default-dynamo-combined-vllm-ae74a2d2
          type: Model
- apiVersion: nvidia.com/v1alpha1
  kind: DynamoWorkerMetadata
  metadata:
    creationTimestamp: "2026-05-06T05:12:06Z"
    generation: 4
    name: dynamo-combined-vllm-prefillworker-ae74a2d2-5bc8f46859-rx8r7
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: false
      controller: true
      kind: Pod
      name: dynamo-combined-vllm-prefillworker-ae74a2d2-5bc8f46859-rx8r7
      uid: 1d8de6bf-d557-4592-80ac-b4ac1b0e9807
    resourceVersion: "249527702"
    uid: a2950496-7450-4720-a1ff-01e907d805e1
  spec:
    data:
      endpoints:
        default-dynamo-combined-vllm-ae74a2d2/prefill/clear_kv_blocks/edd5e6ca943b2:
          component: prefill
          device_type: cpu
          endpoint: clear_kv_blocks
          instance_id: 4184047293645746
          namespace: default-dynamo-combined-vllm-ae74a2d2
          transport:
            tcp: 10.1.3.73:45391/edd5e6ca943b2/clear_kv_blocks
          type: Endpoint
        default-dynamo-combined-vllm-ae74a2d2/prefill/generate/edd5e6ca943b2:
          component: prefill
          device_type: cpu
          endpoint: generate
          instance_id: 4184047293645746
          namespace: default-dynamo-combined-vllm-ae74a2d2
          transport:
            tcp: 10.1.3.73:45391/edd5e6ca943b2/generate
          type: Endpoint
        default-dynamo-combined-vllm-ae74a2d2/prefill/get_perf_metrics/edd5e6ca943b2:
          component: prefill
          device_type: cpu
          endpoint: get_perf_metrics
          instance_id: 4184047293645746
          namespace: default-dynamo-combined-vllm-ae74a2d2
          transport:
            tcp: 10.1.3.73:45391/edd5e6ca943b2/get_perf_metrics
          type: Endpoint
      event_channels: {}
      model_cards:
        default-dynamo-combined-vllm-ae74a2d2/prefill/generate/edd5e6ca943b2:
          card_json:
            context_length: 4096
            display_name: meta-llama/Llama-3.1-8B-Instruct
            gen_config:
              hf_generation_config_json:
                checksum: blake3:0523e4e0a4dd34381ea42fcf70a9e5130722c59b6c8425d5efdecac386c2790d
                path: hf://meta-llama/Llama-3.1-8B-Instruct/generation_config.json
            kv_cache_block_size: 16
            media_decoder: null
            media_fetcher: null
            migration_limit: 0
            model_info:
              hf_config_json:
                checksum: blake3:35526c33568b4823f63765ea29c1b2780659caddec1724adb057cc2495205f51
                path: hf://meta-llama/Llama-3.1-8B-Instruct/config.json
            model_input: Tokens
            model_type: Prefill
            prompt_formatter:
              hf_tokenizer_config_json:
                checksum: blake3:ea3865c7f6f322eeab4d3a61ea83102e19bcfefb5b9022acf16b8ffeaabf21c9
                path: hf://meta-llama/Llama-3.1-8B-Instruct/tokenizer_config.json
            runtime_config:
              data_parallel_size: 1
              data_parallel_start_rank: 0
              enable_eagle: false
              enable_local_indexer: true
              exclude_tools_when_tool_choice_none: true
              max_num_batched_tokens: 8192
              max_num_seqs: 1024
              reasoning_parser: null
              tool_call_parser: null
              total_kv_blocks: 25731
            slug: meta-llama_llama-3_1-8b-instruct
            source_path: meta-llama/Llama-3.1-8B-Instruct
            tokenizer:
              hf_tokenizer_json:
                checksum: blake3:6c628c92d1623f93fe811c3974c81fbc415d776f33cc440d44ee6c7d9ed9e066
                path: hf://meta-llama/Llama-3.1-8B-Instruct/tokenizer.json
          component: prefill
          endpoint: generate
          instance_id: 4184047293645746
          namespace: default-dynamo-combined-vllm-ae74a2d2
          type: Model
kind: List
metadata:
  resourceVersion: ""
