apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.3.73
    conditions:
      ready: false
      serving: false
      terminating: false
    nodeName: hyperpod-i-0a3eb6d3953cceaa7
    targetRef:
      kind: Pod
      name: dynamo-combined-vllm-decodeworker-9dde9687-589995c645-9j9wm
      namespace: default
      uid: c86c4076-3fd7-4df6-a626-f5569d72edd2
    zone: us-east-2c
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-05-06T11:33:41Z"
    creationTimestamp: "2026-05-06T11:25:00Z"
    generateName: dynamo-combined-vllm-decodeworker-9dde9687-
    generation: 7
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: dynamo-combined-vllm-decodeworker-9dde9687
      nvidia.com/dynamo-component: DecodeWorker
      nvidia.com/dynamo-discovery-backend: kubernetes
      nvidia.com/dynamo-discovery-enabled: "true"
      nvidia.com/dynamo-graph-deployment-name: dynamo-combined-vllm
      nvidia.com/dynamo-namespace: default-dynamo-combined-vllm
      nvidia.com/dynamo-worker-hash: 9dde9687
    name: dynamo-combined-vllm-decodeworker-9dde9687-bn2wh
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: dynamo-combined-vllm-decodeworker-9dde9687
      uid: a3e655e9-f20e-4787-8a4d-eb9e6f40b347
    resourceVersion: "249825851"
    uid: f9f16f25-15d1-40e8-9566-12ea9179549e
  ports:
  - name: system
    port: 9090
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.3.195
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hyperpod-i-0a3eb6d3953cceaa7
    targetRef:
      kind: Pod
      name: dynamo-combined-vllm-frontend-64f878c6b5-nw8jv
      namespace: default
      uid: 8a9afe17-dca6-44a8-80fd-d5d71538b48b
    zone: us-east-2c
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-05-06T11:25:14Z"
    creationTimestamp: "2026-05-06T11:25:01Z"
    generateName: dynamo-combined-vllm-frontend-
    generation: 3
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: dynamo-combined-vllm-frontend
      nvidia.com/dynamo-component: Frontend
      nvidia.com/dynamo-discovery-backend: kubernetes
      nvidia.com/dynamo-discovery-enabled: "true"
      nvidia.com/dynamo-graph-deployment-name: dynamo-combined-vllm
      nvidia.com/dynamo-namespace: default-dynamo-combined-vllm
    name: dynamo-combined-vllm-frontend-s7g2f
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: dynamo-combined-vllm-frontend
      uid: 8961df85-e77f-4dfa-b288-82edaf6749eb
    resourceVersion: "249818178"
    uid: 023fb852-cdbc-4461-bd21-8dd4aec09449
  ports:
  - name: http
    port: 8000
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.0.198
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-1-0-198.us-east-2.compute.internal
    targetRef:
      kind: Pod
      name: dynamo-combined-vllm-prefillworker-9dde9687-7bb9dc59c4-8m572
      namespace: default
      uid: 1ab5f77b-f0c4-4026-969f-1a14e2a45a3d
    zone: us-east-2a
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-05-06T11:27:11Z"
    creationTimestamp: "2026-05-06T11:25:01Z"
    generateName: dynamo-combined-vllm-prefillworker-9dde9687-
    generation: 3
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: dynamo-combined-vllm-prefillworker-9dde9687
      nvidia.com/dynamo-component: PrefillWorker
      nvidia.com/dynamo-discovery-backend: kubernetes
      nvidia.com/dynamo-discovery-enabled: "true"
      nvidia.com/dynamo-graph-deployment-name: dynamo-combined-vllm
      nvidia.com/dynamo-namespace: default-dynamo-combined-vllm
      nvidia.com/dynamo-worker-hash: 9dde9687
    name: dynamo-combined-vllm-prefillworker-9dde9687-zss87
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: dynamo-combined-vllm-prefillworker-9dde9687
      uid: b8ad14e6-772d-4686-b922-62691599876f
    resourceVersion: "249819719"
    uid: 39f8897e-b36b-4988-a36e-6ab05b99bc76
  ports:
  - name: system
    port: 9090
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
